apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxd
    ingReq: needed
  name: nginxd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxd
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
